on:
  push:
    branches:
      - main

jobs:
  test:
    name: test_github_var
    runs-on: ubuntu-latest
    steps:
      - name: test_github_var
        run: |
          echo "${{secrets.PSWD}}" > ps
          ssh -i ./ps "root@106.15.39.123" -tt